# -*- coding: utf-8 -*-
DB_NAME = "kbe_XHHY"

PUBLISH_VERSION = 0

DEBUG_BASE = 1

# 表情 扣卡开关
EFFECT_SWITCH = 1

PHP_SERVER_URL = 'http://10.0.0.4:9981/api/'
PHP_SERVER_SECRET = "zDYnetiVvFgWCRMIBGwsAKaqPOUjfNXS"
ACCOUNT_LOGIN_SECRET = "KFZ<]~ct(uYHM%#LABX<>>O6-N(~F#GM" # 登录校验的密钥

PHP_DEBUG_URL	= 'http://localhost:9080/index.php'
CLUB_CARD_MIN	= 24
CLUB_CARD_WARN	= 100

CLIENT_VERSION_WHITE_LIST = ['1.1.5']